### Objectives:-
           Object Oriented Programming -- Python
           Standard Library -- Numpy, Pandas MatplotLib


# class ClassName:
    # some functions and variables
    # function -- used to perfom the specific activity
    # Variable -- data name

In [11]:
def test():
    print("test() for function")
    return
test()

test() for function


In [10]:
 class Demo:
        def test(self):
            print("test() for the class and method")
            return
obj = Demo()
obj.test()

test() for the class and method


In [17]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact = 1
        while(n!=0):
            fact = fact * n
            n = n-1
        return fact
p1 = Demo1()
print(p1.fact(5))

120


In [20]:
class Demo2:
    def Accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(self):
        print("p1 = ",p1)
        print("p2 =",p2)
c1=Demo2()
c1.display()

p1 =  <__main__.Demo1 object at 0x03C572D0>


NameError: name 'p2' is not defined

In [34]:
class Demo2:
   def __init__(self,p1,p2):
       self.p1= p1
       self.p2= p2
       
   def add(self,p1,p2):
        return p1 + p2
   
c1=Demo2(10,20)
print(c1.add(100,200))


300


In [17]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
class employee(person):
    def isemployee(self):
        return True
emp=person("anil")
print(emp.getname(),emp.isemployee())
emp1=person("akhil")
print(emp1.getname(),emp1.isemployee())

anil False
akhil False


In [14]:
lst = {1,2,3,4}
print(lst)

{1, 2, 3, 4}


In [19]:
import numpy as np
lst = [1,2,3,4]
array = np.array(lst)
print(array)

[1 2 3 4]


In [22]:
lst = [1,2,3,4]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [23]:
lst = [1.0,2.5,3.6,9.5]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [29]:
a1=np.array([(1,2,3),(4,5,6,)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [31]:
a1=np.array([(1,2,3),(4,5,6,)])
print(a1)
a1.reshape(3,2)


[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))



[[1 2 3 4 5 6]]


In [34]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [35]:
a1 = np.random.normal(5,0.5,10)
print(a1)

[4.80836566 4.2177421  5.0061183  4.70187149 5.49059268 4.22694474
 5.02182453 6.05283227 4.82319309 5.144319  ]


In [36]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [39]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [40]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [47]:
A =np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [50]:
A =np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2] = 5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [51]:
A =np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3] =14
np.asarray(A)[3][3] =16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [4]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [6]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.arange(1,25,2)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [8]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [12]:
 a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [11]:
a2=np.array([(1,2,3),(4,5,6)])
print("second row:",a2[1])

second row: [4 5 6]


In [10]:
a1=np.array([(1,2,3),(4,5,6,)])
print("second column:",a1[:,2])

second column: [3 6]


In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print("silcing column:",a1[:,2])

silcing column: [3 6]


In [15]:
a1=np.array([(1,2,3),(4,5,6)])
print("silcing row:",a1[:,1])

silcing row: [2 5]


In [13]:
a1 = np.random.normal(5,1,10)
print(a1)

[5.62829065 4.21457332 4.46155513 3.39282067 5.36074052 6.09595687
 5.57184849 5.11919828 5.36207784 5.27341613]


In [19]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[3.82718261 5.00276335 4.27176946 6.00425469 4.99669869 4.0194543
 6.23007102 4.48743659 4.8821704  6.34275015]
Min value= 3.827182606245316
Max value= 6.342750154540594
Mean value= 5.006455127594333
Median value= 4.939434549062207


In [22]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [26]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [28]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.dot(b1,b2)

array([[ 6, 33],
       [15, 72]])

# Pandas Basics

In [33]:
import pandas as pd
dict = {"Name":["Bhanu","Akhil","Srikanth","PR","Sunny","Tan"],
       "EmailID":["bhanuprakash1202@gmail.com","Akhil.kp2000@gmail.com","srikanth@gmail.com","pr@gmail.com","sunny@gmail.com","tan@gmail.com"],
        "MobileNumber":[999,888,777,555,222,111],
        "Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b = pd.DataFrame(dict)
print(b)

       Name                     EmailID  MobileNumber Address
0     Bhanu  bhanuprakash1202@gmail.com           999     Hyd
1     Akhil      Akhil.kp2000@gmail.com           888     Hyd
2  Srikanth          srikanth@gmail.com           777     Hyd
3        PR                pr@gmail.com           555     Hyd
4     Sunny             sunny@gmail.com           222     Hyd
5       Tan               tan@gmail.com           111     Hyd
